<div class="col-lg-2 col-md-2 col-sm-3 col-12 sidebar onlyForLoggedIn">
    <ul class="nav-sidebar admin-nav-bar w-100">
      <li><a href="/admin/dashboard" id="dashboard"><i class="bi bi-layout-text-window-reverse"></i>&nbsp;Dashboard</a></li>
      <hr class="sidebar-divider">
      <li><a href="/book" id="book"><i class="bi bi-book"></i>&nbsp;Books</a></li>
      <li><a href="/author" id="author"><i class="bi bi-pen"></i>&nbsp;Authors</a></li>
      <li><a href="/user/all" id="user"><i class="bi bi-person"></i>&nbsp;Users</a></li>
    </ul>
</div>
