<div class="col-lg-2 col-md-2 col-sm-3 col-12 sidebar onlyForLoggedIn">
    <ul class="nav-sidebar admin-nav-bar w-100">
      <li><a href="/admin/dashboard" id="dashboard">Dashboard</a></li>
      <hr class="sidebar-divider">
      <li><a href="/book" id="book">Books</a></li>
      <li><a href="/author" id="author">Authors</a></li>
      <li><a href="/user/all" id="user">Users</a></li>
    </ul>
</div>
